---
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: weather-app-pvc
 spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: cinder-csi
   resources:
     requests:
       storage: 1Gi
